spring.application.name=ticket-booking-backend
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ticket_booking_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jackson.serialization.write-dates-as-timestamps=false

app.jwt.secret=change-this-secret-key-before-production-use-change-this-secret-key-before-production-use
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:*,http://127.0.0.1:*,http://[::1]:*}
app.auth.expose-debug-otp=${APP_AUTH_EXPOSE_DEBUG_OTP:false}
app.seed-data=true
app.admin.email=${APP_ADMIN_EMAIL:harishgp2005@gmail.com}
app.admin.password=${APP_ADMIN_PASSWORD:miracle69}
app.admin.full-name=${APP_ADMIN_FULL_NAME:Harish GP}
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:465}
spring.mail.username=${SPRING_MAIL_USERNAME:harishgp2005@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:btbgrcvlehosxrrf}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000

app.notifications.email.prefer-resend=${APP_NOTIFICATIONS_EMAIL_PREFER_RESEND:false}
resend.api.key=${RESEND_API_KEY:re_b7CLYvCr_LwMZJkDiwSe5nUJaHCcje8db}
resend.url=${RESEND_URL:https://api.resend.com/emails}
resend.from-email=${RESEND_FROM_EMAIL:PulseSeats <onboarding@resend.dev>}

app.notifications.sms.enabled=${APP_NOTIFICATIONS_SMS_ENABLED:true}
fast2sms.api.key=${FAST2SMS_API_KEY:BJGoPMwUcVl0Mr879P7f9Hs7qzZkCgmUEzfJEFDuHrI8NYo3sZnWe4tAZKuC}
fast2sms.url=${FAST2SMS_URL:https://www.fast2sms.com/dev/bulkV2}

logging.level.com.ticketbooking=INFO
